name: build

on: [push, pull_request]

jobs:
  clippy:
    # Runs Clippy to check for lints in the Rust code
    name: Clippy Lint Check
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: |
          rustup default stable
          rustup component add clippy

      - name: Run Clippy
        run: cargo clippy -- -D warnings

  doc:
    # Builds project documentation, including private items
    name: Docs Check
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check docs
        run: cargo doc --no-deps --document-private-items
        
  build:
    # Builds the examples listed in the matrix
    name: Build Examples
    runs-on: windows-latest

    strategy:
      matrix:
        example: [dinvoke, get_module_and_api, hash, syscall, tampered_syscall]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup default stable

      - name: Build example ${{ matrix.example }}
        env:
          CARGO_PROFILE_RELEASE_PANIC: abort
        run: cargo build --release --example ${{ matrix.example }}

      - name: Upload ${{ matrix.example }}.exe
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.example }}.exe
          path: target/release/examples/${{ matrix.example }}.exe